import turtle
myturtle = turtle.Turtle()
myturtle.forward(100)
myturtle.right(90)
myturtle.forward(100)
myturtle.right(90)
myturtle.forward(100)
myturtle.right(90)
myturtle.forward(100)
turtle.done()